services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: invoice_db
      MYSQL_USER: invoice-mysql-user
      MYSQL_PASSWORD: 6g-[)5Lcs7r]bBMO
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - invoice-network

  backend:
    build: .
    container_name: invoice-backend
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: 35.238.134.199
      DB_PORT: 3306
      DB_USER: invoice-mysql-user
      DB_PASSWORD: 6g-[)5Lcs7r]bBMO
      DB_NAME: invoice_db
      PORT: 5001
    ports:
      - "5001:5001"
    networks:
      - invoice-network

networks:
  invoice-network:
    driver: bridge
